### ISSUE TITLE
Deploy folder

### ISSUE THREAD

**Issue by SamHH** [imperodesign/generator-impero#18]
What to do with it? Nobody outside of Impero will want that generated but we're much better off having it there for ourselves. What solution is there to that?

**Comment by SamHH** [comment]
Also applies to the Dockerfile I suppose.

One option would be a confirm prompt: "Do you want the Impero deploy scripts?" something like that?

**Comment by SamHH** [comment]
@pvalentim Perhaps I could make a quick, private second generator for pulling these in? So you'd do `yo {newProjectName}` for this which anyone could do, then just Imperians could say `yo impero` to fetch the deploy scripts?

**Comment by pvalentim** [comment]
yeah a private generator seems like the best option. We do have a private npm account so we can publish it there

**Comment by SamHH** [comment]
Nearly done, approaching it like this: https://github.com/yeoman/generator/issues/553#issuecomment-45932804
