### ISSUE TITLE
Replace eslint custom rules with standard.js

### ISSUE THREAD

**Issue by pvalentim** [imperodesign/generator-impero#28]
http://standardjs.com/

Any reason this wouldn't work with our setup ?

**Comment by SamHH** [comment]
Seems like it would be okay. React support built-in, TypeScript support via ` standardts`. I'll give it a go!

**Comment by SamHH** [comment]
I think it may make more sense to use this: https://github.com/feross/eslint-config-standard

That way we're sticking with ESLint and can swap configs more easily in the future should we desire, plus altering it at all would be easier. Besides, we'd need the Babel ESLint parser for Standard anyway.

**Comment by SamHH** [comment]
Immediate benefit: Right now by default the standard config forces single quotes in React JSX. Almost all convention says that React should use double quotes a la HTML/XML etc. This is easily overridden with the above. 👍

**Comment by SamHH** [comment]
https://github.com/imperodesign/generator-impero/commit/1b065cf29a1f9b5e83f108e08e617a6a1cb2c8df

Also in alpha10.
