### ISSUE TITLE
Move generated files into subdir (based upon name) a la Git clone

### ISSUE THREAD

**Issue by SamHH** [imperodesign/generator-impero#29]
Right now `yo impero` will generate into the dir you're currently inside of. It would be better if it went into a subdirectory based upon the name you choose.

**Comment by SamHH** [comment]
Appears to be against best practices: http://yeoman.io/authoring/file-system.html

I'll add some sort of warning instead.

**Comment by karltaylor** [comment]
Where does it say it's against best practices? This would be such a good feature and would seriously not fuck up my `./~` again 😂

**Comment by SamHH** [comment]
I took this to mean best practices (among also comments on the web):

`And you can manually set it using generator.destinationRoot('new/path'). But for consistency, you probably shouldn't change the default destination.`

This can still be changed if there's strong consensus.
