### ISSUE TITLE
Remove bundling of CSS styles with Webpack

### ISSUE THREAD

**Issue by MrSlide** [imperodesign/generator-impero#36]
The styles should be decoupled from the generated JS bundle that gets created with Webpack.

CSS should be loaded before anything else on the page loads to avoid re-rendering content. Also, we should everything everything in one massive file, it will only make it take longer to load, and therefore delaying how long it takes to show anything on the page.

Also, in the odd event that the user has JS disabled, the page should still display something instead of unstyled text.

**Comment by pvalentim** [comment]
Agreed. CSS in JS might be a good option for React, but I think that probably falls out of the scope of this generator. We should try to keep this as close to the best practices as possible. In this case I would have CSS get dealt with by gulp.

**Comment by SamHH** [comment]
As far as building it separately is concerned, if I'm understanding you correctly, then that is already happening in the build config.

Not sure what the benefit then is of adding Gulp into the equation - a whole other build tool, the need to use something like BrowserSync for injection instead of Webpack's already-running HMR, etc.

**Comment by MrSlide** [comment]
As far as I can see, the CSS is being included in the main JS bundle. It should be a separate CSS file that can be loaded inside the head tag.

**Comment by SamHH** [comment]
Nope, it's being included within the JS bundle only in dev mode. In build mode it's placed in a separate file. You should see it being conditionally loaded in `head.pug`.

**Comment by SamHH** [comment]
Unless there's any reason to prefer a separate CSS file during development as well (?), this doesn't appear to be an issue to me. As I said before, during build/production CSS will already be detached from JS.

See also: https://github.com/imperodesign/generator-impero/blob/master/generators/app/templates/app/views/components/head.pug#L17
