### ISSUE TITLE
Change promise examples to async/await

### ISSUE THREAD

**Issue by SamHH** [imperodesign/generator-impero#71]
They work fine with import().

**Comment by SamHH** [comment]
Although then you have to specify default like so:

    async function example () {
      const func = await import('./myModule')

      func.default()
    }

Whereas with Promises it's a little less messy, but then you don't get the async goodness..:

    function example () {
      import('./myModule').then(func => func())
    }

Which do we prefer?

**Comment by samhh** [comment]
Going to leave them as they are as in those specific instances the promise flow arguably makes more sense. The examples will hopefully be overhauled at some point anyway.
